### PR TITLE
Formal README.md

### PR DESCRIPTION
**Pull request by anundefineduser**
explains wtf the mod actually is to anyone stumbling across the github, also adds the legal shit so no one gets sued lmao (that was a joke kinda)

### CODE REVIEW

**Comment by CrytosGtag** [comment]
Good PR

**Comment by anundefineduser** [comment]
added a bit more to the readme
currently writing this in science lmao
yay!!!!!

**Comment by anundefineduser** [comment]
rise and shine chin
rise and shine
g-man

**Comment by Chin0303** [comment]
Hmmm

**Comment by anundefineduser** [comment]
closed pr due to chin making readme for next update
i do i have permission for the editor readme though so
image

**Pull request closed without merging**
